### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by sanel** [mikub/titanoboa#1]
Hi @mikub,

Great work! Here is a short talk about current possible license issues: https://www.reddit.com/r/Clojure/comments/a1io36/titanoboa_scalable_and_fault_tolerant_workflow/

Best.

**Comment by mikub** [comment]
Hi @sanel ! Thank you for heads up! 
I looked into the EPL licensing a bit before going with AGPL and from my perspective this would be a case only if I would be making changes to clojure's source code itself (i.e. to the actual source code that is licensed under the EPL).
Then the whole GPL-with-exceptions thing (discussed in the link) could be applicable.
 Since EPL is **weak copyleft license** (unlike **strong copyleft** - e.g. GPL which affects everything it touches), you are free to use EPL licensed libraries with your project and redistribute as far as you dont make changes to the EPL-licensed source code itself (in such case you'd have to make these changes available under EPL).
This is explicitely stated under 1(b) of EPL:

> "_Contributions do not include additions to the Program which: (i) are separate modules of software distributed in conjunction with the Program under their own license agreement, and (ii) are not derivative works of the Program._"

You can also see it being discussed here: https://softwareengineering.stackexchange.com/questions/210043/is-clojure-development-required-to-be-open-source

Maybe I am still missing something, but it would be a bit strange if there was an OSS programming language that would forbid any programs written in it to be anything else than licensed under EPL...

Few examples from other EPL projects:

- JUnit is EPL yet it is being used widely across entire java landscape regardless of open/closed source license.
- KornShell is EPL yet I suspect programs written in it are often closed source

I will leave this open for a bit and please feel free to prove me wrong (as I am far from being lawyer/license expert) - otherwise I will close this after awhile.

Also with all this being said, I am still not entirely decided about AGPL - I went with more restrictive license for starters, but I am planning to look into this depending how I will structure my work and ultimately I may choose something with weak(er) copy left for titanoboa's core parts.

**Comment by sanel** [comment]
Thanks for quick reply.

The things is that Java has exception and Clojure doesn't. Here are few links:

 https://twitter.com/technomancy/status/409868850167951360
 https://groups.google.com/forum/#!msg/clojure/TfPK-ljC46I/YaqwQVYyBAAJ
 https://github.com/littleredcomputer/sicmutils/issues/31

If I got it right (A)GPL + EPL can work only if you distribute project source code, not compiled binary.

**Comment by mikub** [comment]
Hello @sanel ,
so I looked into this more closely and it looks that the only problem is just with the uberjars being available (and linked here) not containing 
1. source code for those libraries that are are licensed with EPL
2. a note regarding OSS 3rd part libraries included and the EPL license included for the reference.
So for now I am removing that part of readme that points to uberjars (as well as the uberjars) and I am leaving only build instructions in the readme which effectively solves the issue (hence I will close it for now): https://github.com/mikub/titanoboa/commit/b1d5067f3dd9817ecdbe67ef14e73f5ce7e161ec

On a side note:
After some review of the licenses it seems to me that still the incompatibility of the licenses is if you want to use EPL licensed source code in an AGPL source code and really mix them together:
https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean
 
Including libraries aside and even inside seems to be fine (https://www.eclipse.org/legal/eplfaq.php#PROPPROD) :

> When I incorporate a portion of a Program licensed under the EPL into my own proprietary product distributed in object code form, can I use a single license for the full product, in other words, covering the portion of the Program plus my own code?
Yes. The object code for the product may be distributed under a single license as long as it references the EPL portion and complies, for that portion, with the terms of the EPL.

- so as far as you still share the source code for that library that is licensed under EPL and do not attempt to license it under different license (but it still applies ONLY to that library/code/framework - so it does not infect your code as GPL would; this is also why the EPL is more permissive than GPL) .

The gray area I guess is only that the uberjar mixes everything together, so one might want to either: 
a) add exception to the license as in https://github.com/metabase/metabase/commit/666b1b453a71a1fca19e7b81739a58ce7fa45a14#diff-61e0bdf7e1b43c5c93d9488b22e04170
or
b) make it explicit that AGPL license only covers part of what you distribute
c) simply ship EPL jars separately
